### ISSUE TITLE
while starting the sunspot server this error occuring undefined method `empty?' for :needs:Symbol

### ISSUE THREAD

**Issue by umamahe** [sunspot/sunspot#344]
I'm working with rails 2 and sunspot_rails 1.1.0

while starting the sunspot server
rake sunspot:solr:start

the following error
undefined method `empty?' for :needs:Symbol

In my local development machine i'm using rake 0.9.2.2 working fine

while moving to production server rake version 10.0.3 showing the following error.

is that rake issue

This is my rakefile

require(File.join(File.dirname(FILE), 'config', 'boot'))

require 'rake'
require 'sunspot/rails/tasks'
require 'rake/testtask'
require 'rake/rdoctask'
require 'tasks/rails'
require 'spec/rake/spectask'

Load the Sunspot rake tasks
require 'sunspot/rails/tasks'
