### ISSUE TITLE
`method_missing': undefined method `searchable' in 1.3

### ISSUE THREAD

**Issue by frankel** [sunspot/sunspot#151]
After upgrading from 1.2 to 1.3, and start to run rails(3.1.3), it throws an error of 

   method_missing': undefined method `searchable' for # Class:0x007fd3a9140170 (NoMethodError)

Do I need to change someting?
