### ISSUE TITLE
Pagination broken on Kaminari 0.14

### ISSUE THREAD

**Issue by fred** [sunspot/sunspot#280]
Hi, 
I'm not sure if this is correct place to post this bug, but looks like pagination is broken on latest kaminari 0.14.0
Everything works fine on kaminari 0.13.0

error:

   ActionView::Template::Error (undefined method `total_pages' for #Sunspot::Search::StandardSearch:0x00000008b97488):

what do you think?
