### PR TITLE
Fix travis error last comment and uninitialized constant r solr connection

### PR DESCRIPTION
**Pull request by rocket-turtle**
1. RSolr 2.0 is released so bundler automatically installs the latest version. Test also against older RSolr version.
-> NoMethodError: undefined method `last_comment' for #Rake::Application:0x00000000f63650>
2. The method `last_comment` which is called from rspec-core was removed from rake 11. https://github.com/rspec/rspec-core/commit/8e723fc805e901ac4fa5483837138b175d411d6e 
-> /home/travis/build/sunspot/sunspot/sunspot_rails/lib/sunspot/rails/solr_logging.rb:50:in `<top (required)>': uninitialized constant RSolr::Connection (NameError)
3. Fix Gem::InstallError: nokogiri ~> 1.7 requires Ruby version >= 2.1.0.
4. allow_failures for rails 5.0 because it doesn't work with rspec-rails-2.14.2 undefined method 'alias_method_chain'

### CODE REVIEW

**Comment by rocket-turtle** [comment]
3. Fix Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.

**Comment by rocket-turtle** [comment]
Last error has something to do with the old rspec version:
```
/home/travis/build/sunspot/sunspot/sunspot_rails/tmp/rails_5_0_app/vendor/bundle/gems/rspec-rails-2.14.2/lib/rspec/rails/matchers/have_extension.rb:28:in `block in <module:HaveExtensions>': undefined method `alias_method_chain' for RSpec::Matchers::BuiltIn::Have:Class (NoMethodError)
Did you mean?  alias_method
```

If your interested I could look into the rspec update.

**Comment by vakuum** [comment]
@bragboy: This pull request would make Travis CI green again. :tada:

**Comment by bragboy** [comment]
@rocket-turtle : Thank you
